{
  "formatVersion": "1.1",
  "component": {
    "group": "com.isroot",
    "module": "lmbridge",
    "version": "0.0.38",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "lmbridge-0.0.38.aar",
          "url": "lmbridge-0.0.38.aar",
          "size": 100696,
          "sha512": "62572e34e4247beaa3b94a9e3246e0a3fb7025da9d5705eb92376059184e11c645b7cf23cec6070a63549167679ea1b65845abfaa910e3e96eec2922dda9024f",
          "sha256": "953764f3b3e51bd351dbf81ec4f089a5f8bb3b3825fd879425f7d43a0ad4d0c9",
          "sha1": "832ab1f1d08a73d1c69ec074514f1d0a47e5f29a",
          "md5": "bc69fdff24239ac465b4a23d0fdea02e"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.google.ai.edge.litertlm",
          "module": "litertlm-android",
          "version": {
            "requires": "0.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "lmbridge-0.0.38.aar",
          "url": "lmbridge-0.0.38.aar",
          "size": 100696,
          "sha512": "62572e34e4247beaa3b94a9e3246e0a3fb7025da9d5705eb92376059184e11c645b7cf23cec6070a63549167679ea1b65845abfaa910e3e96eec2922dda9024f",
          "sha256": "953764f3b3e51bd351dbf81ec4f089a5f8bb3b3825fd879425f7d43a0ad4d0c9",
          "sha1": "832ab1f1d08a73d1c69ec074514f1d0a47e5f29a",
          "md5": "bc69fdff24239ac465b4a23d0fdea02e"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "lmbridge-0.0.38-sources.jar",
          "url": "lmbridge-0.0.38-sources.jar",
          "size": 21475,
          "sha512": "640aa27a57ee41cc49912c2f9b03626d893174f4f1779897921b5e5ee6c083ae38298dd037d69afd47e81238a83275569c316238cfa4940b07c55c1025f0657c",
          "sha256": "dbcbaa8b061db1e494958ca9614dd864411dbb5e4faebbc7028130d1835b52c6",
          "sha1": "1e3cac9262758b3be62c5826a1e8ff397a62866e",
          "md5": "ba20b7e31f48723282fc5be11bd41c4e"
        }
      ]
    }
  ]
}
