{
  "formatVersion": "1.1",
  "component": {
    "group": "com.isroot",
    "module": "lmbridge",
    "version": "0.0.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "lmbridge-0.0.24.aar",
          "url": "lmbridge-0.0.24.aar",
          "size": 95513,
          "sha512": "ce1839b0ec2c718ada05321929c8d9d599270705e3d943b3817aa593dd36b6cd370140110709253063f8ee11e5314e767defac07c9ecbcd917fe1d68acdc6514",
          "sha256": "cce12e554827c697699fe3c6c576171a7bd07887da64dedb895f7a018694f3b9",
          "sha1": "dbf903aadd16975cda4e24f61e4e5600ac84ae33",
          "md5": "1d4f9ce7ada51f9ab2da0afddaa04771"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.google.ai.edge.litertlm",
          "module": "litertlm-android",
          "version": {
            "requires": "0.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "lmbridge-0.0.24.aar",
          "url": "lmbridge-0.0.24.aar",
          "size": 95513,
          "sha512": "ce1839b0ec2c718ada05321929c8d9d599270705e3d943b3817aa593dd36b6cd370140110709253063f8ee11e5314e767defac07c9ecbcd917fe1d68acdc6514",
          "sha256": "cce12e554827c697699fe3c6c576171a7bd07887da64dedb895f7a018694f3b9",
          "sha1": "dbf903aadd16975cda4e24f61e4e5600ac84ae33",
          "md5": "1d4f9ce7ada51f9ab2da0afddaa04771"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "lmbridge-0.0.24-sources.jar",
          "url": "lmbridge-0.0.24-sources.jar",
          "size": 19173,
          "sha512": "4ece94aa8ae4c37d129d8b26999b512b789c1809a6f90085b163b88fdb8b076badabd10730eb1050fdd842c7e204d1cf0c584ae36a65cb7b172977f59ec61bde",
          "sha256": "35ee9eb727cc6d28aed917a5e2890cfc7b0dd1232b6694aef7907e7387260832",
          "sha1": "a3422127ceecc8705d00ad06d25d87b4b951cdc4",
          "md5": "15b481e08ee967740fde4e113300ec2c"
        }
      ]
    }
  ]
}
