{
  "formatVersion": "1.1",
  "component": {
    "group": "com.isroot",
    "module": "lmbridge",
    "version": "0.0.45",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "lmbridge-0.0.45.aar",
          "url": "lmbridge-0.0.45.aar",
          "size": 2258106,
          "sha512": "b189fb8d4ca191eb6a72a45922ad05f8cc4035893220b68a6508af4731e969b34ba1bd12b363a21281d5f360ce1b9f9ae7b90af04a95fbf2701f8044010e6985",
          "sha256": "bd56b59c6919ca5e54060d32529e538e3693819750d15688f4bd24a000952136",
          "sha1": "dac6b0fccf3fd6e6c14afbb07f9ece3aeba8e6a5",
          "md5": "da1e4481798c32e3ce704bfcf6ebd6c5"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.google.ai.edge.litertlm",
          "module": "litertlm-android",
          "version": {
            "requires": "0.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "lmbridge-0.0.45.aar",
          "url": "lmbridge-0.0.45.aar",
          "size": 2258106,
          "sha512": "b189fb8d4ca191eb6a72a45922ad05f8cc4035893220b68a6508af4731e969b34ba1bd12b363a21281d5f360ce1b9f9ae7b90af04a95fbf2701f8044010e6985",
          "sha256": "bd56b59c6919ca5e54060d32529e538e3693819750d15688f4bd24a000952136",
          "sha1": "dac6b0fccf3fd6e6c14afbb07f9ece3aeba8e6a5",
          "md5": "da1e4481798c32e3ce704bfcf6ebd6c5"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "lmbridge-0.0.45-sources.jar",
          "url": "lmbridge-0.0.45-sources.jar",
          "size": 19785,
          "sha512": "dc0f05f7da5ab2a37b271566e56be1794474c8bfc50242430d9eb677cf33b03e5c986e8fd3af0ce62edb2288ea4224976c97d939cd20db1ddce95c410c09fe77",
          "sha256": "5c2573a8c8218b660972352c302c57581e89acd9f935bd022db9274b3ecb6420",
          "sha1": "054a123cacc34ed3b22a5947c42c1a42261a8ed2",
          "md5": "3df17d9a087bca3cda8844be18b853a1"
        }
      ]
    }
  ]
}
