{
  "formatVersion": "1.1",
  "component": {
    "group": "com.isroot",
    "module": "lmbridge",
    "version": "0.0.44",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "lmbridge-0.0.44.aar",
          "url": "lmbridge-0.0.44.aar",
          "size": 579431,
          "sha512": "0c3e9a92bac9857bea5229ed20a0d3df58708c03e7968ef828f6b3b8d4d4ebf5b1a7465a806db9657ad486b1d4621d6b61c6fcd32755b40e4fd6b1104ef8f05e",
          "sha256": "a0cba2ba8b0d8b46d75ef1b0ffc287807060b399ec513933a4b24bc70566b0dc",
          "sha1": "9b479455519619d6289110e531f694b0c7ec4595",
          "md5": "59b059421381142a776b0cfab92fa7c6"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.google.ai.edge.litertlm",
          "module": "litertlm-android",
          "version": {
            "requires": "0.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "lmbridge-0.0.44.aar",
          "url": "lmbridge-0.0.44.aar",
          "size": 579431,
          "sha512": "0c3e9a92bac9857bea5229ed20a0d3df58708c03e7968ef828f6b3b8d4d4ebf5b1a7465a806db9657ad486b1d4621d6b61c6fcd32755b40e4fd6b1104ef8f05e",
          "sha256": "a0cba2ba8b0d8b46d75ef1b0ffc287807060b399ec513933a4b24bc70566b0dc",
          "sha1": "9b479455519619d6289110e531f694b0c7ec4595",
          "md5": "59b059421381142a776b0cfab92fa7c6"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "lmbridge-0.0.44-sources.jar",
          "url": "lmbridge-0.0.44-sources.jar",
          "size": 19785,
          "sha512": "dc0f05f7da5ab2a37b271566e56be1794474c8bfc50242430d9eb677cf33b03e5c986e8fd3af0ce62edb2288ea4224976c97d939cd20db1ddce95c410c09fe77",
          "sha256": "5c2573a8c8218b660972352c302c57581e89acd9f935bd022db9274b3ecb6420",
          "sha1": "054a123cacc34ed3b22a5947c42c1a42261a8ed2",
          "md5": "3df17d9a087bca3cda8844be18b853a1"
        }
      ]
    }
  ]
}
