{
  "formatVersion": "1.1",
  "component": {
    "group": "com.isroot",
    "module": "lmbridge",
    "version": "0.0.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "lmbridge-0.0.20.aar",
          "url": "lmbridge-0.0.20.aar",
          "size": 80934,
          "sha512": "d8e65bed99c2d07482bb40c781588b137734e1e57b7348fb2f99730e8021816f6b01544f4030c33cdd1fb0440ad171536e0ca1840130ecec38070079d20ff844",
          "sha256": "462a00b069eb89a4dd7ee211ad23ad91135cc088594fbbdcbc404fc715069527",
          "sha1": "474be7748460429b363f646e9ca6c45637912a53",
          "md5": "fca64742d0dc06489bf4161276de0449"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.google.ai.edge.litertlm",
          "module": "litertlm-android",
          "version": {
            "requires": "0.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "lmbridge-0.0.20.aar",
          "url": "lmbridge-0.0.20.aar",
          "size": 80934,
          "sha512": "d8e65bed99c2d07482bb40c781588b137734e1e57b7348fb2f99730e8021816f6b01544f4030c33cdd1fb0440ad171536e0ca1840130ecec38070079d20ff844",
          "sha256": "462a00b069eb89a4dd7ee211ad23ad91135cc088594fbbdcbc404fc715069527",
          "sha1": "474be7748460429b363f646e9ca6c45637912a53",
          "md5": "fca64742d0dc06489bf4161276de0449"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "lmbridge-0.0.20-sources.jar",
          "url": "lmbridge-0.0.20-sources.jar",
          "size": 19039,
          "sha512": "cab57ebd2308031e7d66df97856c35ae78b56a6c8e2ddbaa3551a71185ad24a00b122688ce4e928a85648fb8823c0493a0a48b328515487abb9ab9518cbf80e5",
          "sha256": "843effca85bd97dd79079019203fec949fc334b0c1d80225baecae5257fdd969",
          "sha1": "3ba4c5c175ad998dc782a982d993e9d5cd20a11b",
          "md5": "ae1cac6c4c745d4bc45d15eb26e2934f"
        }
      ]
    }
  ]
}
