{
  "formatVersion": "1.1",
  "component": {
    "group": "com.isroot",
    "module": "lmbridge",
    "version": "0.0.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "lmbridge-0.0.25.aar",
          "url": "lmbridge-0.0.25.aar",
          "size": 106449,
          "sha512": "795e4f3156e1aa7382429c88dc2b098f8e56616861000f7bcd0e4f82ea47ac39a29f611bc48400d4d7d8b4149dc60b26cdb56f59ebf955eead5d578581025620",
          "sha256": "ec5325210d662fddc45e458b92a62fadeb08029a31a1889fb901a6d7c87ddb83",
          "sha1": "67f2d2cecc321024347d4e16eb562937f4b60472",
          "md5": "22cd1b9eaae921cefdad9387d5e9ccf5"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.google.ai.edge.litertlm",
          "module": "litertlm-android",
          "version": {
            "requires": "0.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "lmbridge-0.0.25.aar",
          "url": "lmbridge-0.0.25.aar",
          "size": 106449,
          "sha512": "795e4f3156e1aa7382429c88dc2b098f8e56616861000f7bcd0e4f82ea47ac39a29f611bc48400d4d7d8b4149dc60b26cdb56f59ebf955eead5d578581025620",
          "sha256": "ec5325210d662fddc45e458b92a62fadeb08029a31a1889fb901a6d7c87ddb83",
          "sha1": "67f2d2cecc321024347d4e16eb562937f4b60472",
          "md5": "22cd1b9eaae921cefdad9387d5e9ccf5"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "lmbridge-0.0.25-sources.jar",
          "url": "lmbridge-0.0.25-sources.jar",
          "size": 19003,
          "sha512": "7ccbd6de17c372f88aed4196715be37f6f3a17f0319bfc0ede65824fcd2b9d84b766d594a53b1f1659421036e23f6de96658f815017bac321c9f2ebd026cd0ba",
          "sha256": "8b9379a1e0104de52cb35d4f0afe41715c0753478b5d4d510f23cc5105074473",
          "sha1": "8bfec72c35cbe3f5e4dafdcfd1027f2fc1e9d6a5",
          "md5": "c63208b26e9396fa98b07d3723178777"
        }
      ]
    }
  ]
}
