{
  "formatVersion": "1.1",
  "component": {
    "group": "com.isroot",
    "module": "lmbridge",
    "version": "0.0.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "lmbridge-0.0.16.aar",
          "url": "lmbridge-0.0.16.aar",
          "size": 80889,
          "sha512": "af104492acbd54bd865dd49b24a7fa5b1763206e0136ca746e88dd0ec29c70e80a04a0e6e2bc6d1a202643f35fdf1ad02183686f54e63cb45037f9f3bd76ffc6",
          "sha256": "929c7fd630da7e272d844297fd0f51a75346d0d96d4aecd3420ac3d8b52de529",
          "sha1": "5274d16511f64333423ffc8f3a4d1a43e1881ad5",
          "md5": "807cd4ccabfb8b9116b55b84e95416a1"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.google.ai.edge.litertlm",
          "module": "litertlm-android",
          "version": {
            "requires": "0.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "lmbridge-0.0.16.aar",
          "url": "lmbridge-0.0.16.aar",
          "size": 80889,
          "sha512": "af104492acbd54bd865dd49b24a7fa5b1763206e0136ca746e88dd0ec29c70e80a04a0e6e2bc6d1a202643f35fdf1ad02183686f54e63cb45037f9f3bd76ffc6",
          "sha256": "929c7fd630da7e272d844297fd0f51a75346d0d96d4aecd3420ac3d8b52de529",
          "sha1": "5274d16511f64333423ffc8f3a4d1a43e1881ad5",
          "md5": "807cd4ccabfb8b9116b55b84e95416a1"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "lmbridge-0.0.16-sources.jar",
          "url": "lmbridge-0.0.16-sources.jar",
          "size": 19035,
          "sha512": "82f15c3ae977aabd4e4c4ea750e6b9067f5ad2b5e7aaa806ea664b8d83d02d1b228d0cab9d01cc05fbfb0acc7fc49e4a545d4d349d00ab1bd6448c940777e3e0",
          "sha256": "8c154832940e7fd794bc5477bf97eaee9bd53581a0b5c3c7f669ed6b8ab6d11e",
          "sha1": "4568fb6c26cd77102c8ad812aa4c3c6aea23a79f",
          "md5": "7ed189d7dc7372a3bb2436dc94016cf4"
        }
      ]
    }
  ]
}
