{
  "formatVersion": "1.1",
  "component": {
    "group": "com.isroot",
    "module": "lmbridge",
    "version": "0.0.41",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "lmbridge-0.0.41.aar",
          "url": "lmbridge-0.0.41.aar",
          "size": 78786,
          "sha512": "9cf77ac25e92307908e85cc68efbccb2aebdfd8630ae49b7e3b4ad82180f529cd96320b3782265e9b72a146fb93eecd15cbc21dcd6e3da76cdbeee6ccb23ca1d",
          "sha256": "40b278a479c80032432c808fcf7b087e3d20d4d4160322e8ed8406cf6bc5ba67",
          "sha1": "58846116d8739aef99a0d9d0993ece56cdc23a52",
          "md5": "011e445812ec7abe26e1c543e916f341"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.google.ai.edge.litertlm",
          "module": "litertlm-android",
          "version": {
            "requires": "0.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "lmbridge-0.0.41.aar",
          "url": "lmbridge-0.0.41.aar",
          "size": 78786,
          "sha512": "9cf77ac25e92307908e85cc68efbccb2aebdfd8630ae49b7e3b4ad82180f529cd96320b3782265e9b72a146fb93eecd15cbc21dcd6e3da76cdbeee6ccb23ca1d",
          "sha256": "40b278a479c80032432c808fcf7b087e3d20d4d4160322e8ed8406cf6bc5ba67",
          "sha1": "58846116d8739aef99a0d9d0993ece56cdc23a52",
          "md5": "011e445812ec7abe26e1c543e916f341"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "lmbridge-0.0.41-sources.jar",
          "url": "lmbridge-0.0.41-sources.jar",
          "size": 19785,
          "sha512": "dc0f05f7da5ab2a37b271566e56be1794474c8bfc50242430d9eb677cf33b03e5c986e8fd3af0ce62edb2288ea4224976c97d939cd20db1ddce95c410c09fe77",
          "sha256": "5c2573a8c8218b660972352c302c57581e89acd9f935bd022db9274b3ecb6420",
          "sha1": "054a123cacc34ed3b22a5947c42c1a42261a8ed2",
          "md5": "3df17d9a087bca3cda8844be18b853a1"
        }
      ]
    }
  ]
}
