{
  "formatVersion": "1.1",
  "component": {
    "group": "com.isroot",
    "module": "lmbridge",
    "version": "0.0.26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "lmbridge-0.0.26.aar",
          "url": "lmbridge-0.0.26.aar",
          "size": 98462,
          "sha512": "e2ccb7a0fa0ed8f2fa9612e8961068a282e21771fa04e1d5a250adc80ec2d77d269d6ea66866876077a35304ceab0573b949153f5ee4192b47b6052cdfa1f659",
          "sha256": "8352363f4422bb62b157de03fcc9d1d9fc1a7a3ccdfb17401d9265a646fcc7fa",
          "sha1": "34a85aa7ec077beb3e341229c9b4183f1897c823",
          "md5": "204bd6ac5b54fc90ccf9ad6eb0575974"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.google.ai.edge.litertlm",
          "module": "litertlm-android",
          "version": {
            "requires": "0.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "lmbridge-0.0.26.aar",
          "url": "lmbridge-0.0.26.aar",
          "size": 98462,
          "sha512": "e2ccb7a0fa0ed8f2fa9612e8961068a282e21771fa04e1d5a250adc80ec2d77d269d6ea66866876077a35304ceab0573b949153f5ee4192b47b6052cdfa1f659",
          "sha256": "8352363f4422bb62b157de03fcc9d1d9fc1a7a3ccdfb17401d9265a646fcc7fa",
          "sha1": "34a85aa7ec077beb3e341229c9b4183f1897c823",
          "md5": "204bd6ac5b54fc90ccf9ad6eb0575974"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "lmbridge-0.0.26-sources.jar",
          "url": "lmbridge-0.0.26-sources.jar",
          "size": 18985,
          "sha512": "47cb6ca50b92e2e1b82a8199ce96de4d24326fa050c293e8109624aeb1db610f95e0f762f47b48bc22821397a4cd115d0d7aa634571df921e53971568e2798ed",
          "sha256": "9852954b368a5070496b0cd8316f455e0a5b9c16ad2d2f80f53372fc8b14a9b3",
          "sha1": "ce7172561aef07cea2e002a72952f3f4da44c8bc",
          "md5": "28b773dfb89a565a7063f9be279dccd3"
        }
      ]
    }
  ]
}
